#!/bin/bash
#
# This Works is placed under the terms of the Copyright Less License,
# see file COPYRIGHT.CLL.  USE AT OWN RISK, ABSOLUTELY NO WARRANTY.

cd "`dirname "$0"`" || exit

out="tmp/todo$$"

OOPS()
{
echo "OOPS $*" >&2
rm -f "$out"
exit 1
}

mins="$1"
case "$mins" in
[0-9]|[0-9]*[0-9])	shift || OOPS missing arg;;
*)			mins=0;;
esac

for script
do
	exec="${script##*/}"
        case "$exec" in
	[0-9]|[0-9]*[0-9])	;;
	*..*|*/*)	OOPS "$script";;
	save|-)		echo "$exec"; continue;;
	*)		[ -s "script/LINKS/$exec" ] && read -r exec < "script/LINKS/$exec"
			exec="${exec//:/ }"
			[ -s "script/${exec%% *}" ] || OOPS "unknown $exec"
			;;
	esac
	echo "$exec"
done > "$out"

./in.inc "$mins" "$out" || OOPS failed

exec ./list

