#!/bin/bash

cd "$(dirname "$(readlink -e "$0")")/.." || exit

trig()
{
printf '%(%Y%m%d-%H%M%S)T' || exit
v="$(./sendsock.py "$1" 'run heartbeat')"
printf ' %q:%q %q\n' "$1" "$?" "$v" || exit
read -t60 t && exit
}

while	:
do
	for a in sub/*
	do
		[ -d "$a" ] || { sleep 1; continue; }
		trig "${a##*/}"
	done
done

